In [1]:
# This lesson is about data analysis

In [2]:
import numpy

In [3]:
numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [4]:
# What would the command look like if the data is separated by a ";"?
# numpy.loadtxt(fname="inflammation-01.csv", delimiter=";")

In [5]:
data = numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [6]:
# Let's see what object we are working with
print(type(data))

<class 'numpy.ndarray'>


In [7]:
print(data.shape)

(60, 40)


In [8]:
print("the first value is: ", data[0, 0])

the first value is:  0.0


In [9]:
print("the middle value is: ", data[29, 19])

the middle value is:  16.0


In [10]:
# Can you slice the data to print out the first 3 patients and their first 9 days?

In [12]:
print(data[0:3, 0:9])

[[0. 0. 1. 3. 1. 2. 4. 7. 8.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5.]]


In [13]:
# Look at the mean of the dataset
print(numpy.mean(data))

6.14875


In [15]:
# Not all functions need arguments
import time
print("number of seconds since the 1st of January, 1970: ", time.time())

number of seconds since the 1st of January, 1970:  1762862496.3332922


In [16]:
maxval, minval, stdval = numpy.amax(data), numpy.amin(data), numpy.std(data)
print("maximum inflammation: ", maxval)
print("miniumum inflammation: ", minval)
print("standard deviation: ", stdval)

maximum inflammation:  20.0
miniumum inflammation:  0.0
standard deviation:  4.613833197118566


In [17]:
numpy.indices? # alternative is help(numpy.indices)

Signature: numpy.indices(dimensions, dtype=<class 'int'>, sparse=False)
Docstring:
Return an array representing the indices of a grid.

Compute an array where the subarrays contain index values 0, 1, ...
varying only along the corresponding axis.

Parameters
----------
dimensions : sequence of ints
    The shape of the grid.
dtype : dtype, optional
    Data type of the result.
sparse : boolean, optional
    Return a sparse representation of the grid instead of a dense
    representation. Default is False.

    .. versionadded:: 1.17

Returns
-------
grid : one ndarray or tuple of ndarrays
    If sparse is False:
        Returns one array of grid indices,
        ``grid.shape = (len(dimensions),) + tuple(dimensions)``.
    If sparse is True:
        Returns a tuple of arrays, with
        ``grid[i].shape = (1, ..., 1, dimensions[i], 1, ..., 1)`` with
        dimensions[i] in the ith place

See Also
--------
mgrid, ogrid, meshgrid

Notes
-----
The output shape in the dense case is obtain

In [18]:
# We want one patient, and all their data (one row, all columns)
patient_0 = data[0, :] 
print("maximum inflammation for patient 0: ", numpy.amax(patient_0))

maximum inflammation for patient 0:  18.0


In [19]:
patients = data[1:4, 2:6]
print(patients)

[[2. 1. 2. 1.]
 [1. 3. 3. 2.]
 [2. 0. 4. 2.]]


In [20]:
# we use the axis argument set to 1 to apply to all columns
print(numpy.amax(data, axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [22]:
print(numpy.amax(data, axis=1).shape)

(60,)


In [23]:
# We want the average per day across all patients
print(numpy.mean(data, axis=0))
print(numpy.mean(data, axis=0).shape)

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
(40,)


In [26]:
# Can you flex you slicing skills?
# Can you cut up the following sentence to spell "Hello world"?

string = "Matthew won't read the lesson"
print(string[4:6], string[-6], string[-6], string[-2], " ", string[8:10], string[14], string[-6], string[-12])

he l l o   wo r l d


In [28]:
# Can you rearrange the following matrix to use the first and last columns and stack them in to a 3x2 array instead?
A = numpy.array([[1, 2 ,3], [4,5,6], [7,8,9]])
print("Matrix A: ", A)
B = numpy.array([A[:, 0], A[:, 2]])
print("Matrix B: ", B)

Matrix A:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:  [[1 4 7]
 [3 6 9]]


In [ ]:
# The numpy.diff() function takes an array and returns the differences between two successive values. Let's use it to examine
# the changes each day across the fist week of patient 3

patient3_week1 = data[3, :7]