# Functions - Part 2

In this section we cover testing, default values in functions, argument order and documentation. 

In [3]:
# Let's write an exmaple function to play around with
def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data) + target_mean_value)

# Function should shift the mean to a value we choose

In [7]:
import numpy
# This creates a 2x2 matrix filled with zeros
z = numpy.zeros((2,2))
# ?numpy.zeros
print(z)

[[0. 0.]
 [0. 0.]]


In [8]:
# Testing that our function works as we expect it to
# Writing functions doesn't guarantee no mistakes, but it is easier to find them than in 30 versions of slightly different code
print(offset_mean(z, 3))

[[3. 3.]
 [3. 3.]]


In [10]:
# Let's test it on one of the datasets we have been using in the sessions
# Remember that the path to your data is possibly not the same as mine
# You can either provide the full path (usually from your C drive) or your relative path, the path starting from where your code is running
data = numpy.loadtxt(fname="inflammation-01.csv", delimiter = ",")
print(offset_mean(data, 0))

[[-6.14875 -6.14875 -5.14875 ... -3.14875 -6.14875 -6.14875]
 [-6.14875 -5.14875 -4.14875 ... -5.14875 -6.14875 -5.14875]
 [-6.14875 -5.14875 -5.14875 ... -4.14875 -5.14875 -5.14875]
 ...
 [-6.14875 -5.14875 -5.14875 ... -5.14875 -5.14875 -5.14875]
 [-6.14875 -6.14875 -6.14875 ... -6.14875 -4.14875 -6.14875]
 [-6.14875 -6.14875 -5.14875 ... -5.14875 -5.14875 -6.14875]]


In [12]:
# checking the stats
print("original min, mean, and max are:", numpy.amin(data), numpy.mean(data), numpy.amax(data))

original min, mean, and max are: 0.0 6.14875 20.0


In [13]:
# Offsetting the data and comparing the stats now
offset_data = offset_mean(data, 0)
print("min, mean, max of offset data are: ", 
      numpy.amin(offset_data), numpy.mean(offset_data), 
      numpy.amax(offset_data))

min, mean, max of offset data are:  -6.14875 2.842170943040401e-16 13.85125


In [14]:
# when rounding we see that the mean is essentially zero
round(numpy.mean(offset_data), 1)

0.0

In [15]:
# Adding our own documentation
def offset_mean(data, target_mean_value):
    """Return a new array containing the original data with its mean offset
    to match the desired value."""
    return (data - numpy.mean(data)) + target_mean_value

In [16]:
# You can use the help function on any function to get a print out of its doc(umentation) string
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value)
    Return a new array containing the original data with its mean offset
    to match the desired value.



In [17]:
# The ? works similarly to the help function
?offset_mean

Signature: offset_mean(data, target_mean_value)
Docstring:
Return a new array containing the original data with its mean offset
to match the desired value.
File:      c:\users\tis254\appdata\local\temp\ipykernel_18192\2841305062.py
Type:      function

In [18]:
# Most of the time we have been writing fname and then the path to the file
# But we can get it to load without using fname
numpy.loadtxt("inflammation-01.csv", delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [19]:
# This doesn't work because the delimiter is not the second argument
# The second argument can't take "," as a value and so the process breaks
# When using positional arguments it is important to make sure you know which argument you are providing a value to
numpy.loadtxt("inflammation-01.csv", ",")

SyntaxError: invalid syntax (<unknown>, line 1)

In [20]:
# We need to name delimiter as there are other arguments before it
# Not using names means we rely on the position of the argument
# ?numpy.loadtxt # uncomment this to read the documentation of this function

Signature:
numpy.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str

In [21]:
# Now we have added a default value for the target_mean_value argument
# Defaults are usually best set to be what the standard use of the function would need
# e.g. if you have a function that plots some data showing tidal recordings
## the default might be to use a blue highlight for high tide and a red one for low tide
### You can set these as the default as most of the time that is what is needed

def offset_mean(data, target_mean_value = 0.0):
    """Return a new array containing the original data with its mean
    offset to match the desired value, (0 by default)."""
    return (data - numpy.mean(data)) + target_mean_value
    

In [22]:
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value=0.0)
    Return a new array containing the original data with its mean
    offset to match the desired value, (0 by default).



In [23]:
# WE are adding a little more context to the function with an example
# An example can help to clarify how people can use the function
## what they should put in and what they can expect out
### it can also be a way to make sure the function is working correctly

def offset_mean(data, target_mean_value = 0.0):
    """Return a new array containing the original data with its mean
    offset to match the desired value, (0 by default).
    Examples
    ------
    >>>offset_mean([1,2,3])
    array([-1., 0., 1.])"""
    return (data - numpy.mean(data)) + target_mean_value

In [25]:
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value=0.0)
    Return a new array containing the original data with its mean
    offset to match the desired value, (0 by default).
    Examples
    ------
    >>>offset_mean([1,2,3])
    array([-1., 0., 1.])



In [3]:


def offset_mean(data, target_mean_value: float | int = 0.0):
    """Return a new array containing the original data with its mean
    offset to match the desired value, (0 by default).
    
    args:
    data - Dataset in the form of a numpy array
    target_mean_value - A number (float or integer) that we want to change 
                        the mean of the array to

    Returns: a new array containing the original data with its mean
    offset to match the desired value
    
    Examples
    ------
    >>>offset_mean([1,2,3])
    array([-1., 0., 1.])"""
    return (data - numpy.mean(data)) + target_mean_value

In [5]:
# Default values can be overwritten
test_data = numpy.zeros((2,2))
print(offset_mean(test_data, 3))

[[3. 3.]
 [3. 3.]]


In [6]:
# A simple function with 3 different arguments, each with a default value
def display(a=1, b=2, c=3):
    print("a: ", a, "b: ", b, "c:", c)

In [7]:
# Looking at how we can use positional arguments and what the default values do
print("no parameters", display(), "one parameter", display(55))
print("two parameters", display(55, 66))

a:  1 b:  2 c: 3
a:  55 b:  2 c: 3
no parameters None one parameter None
a:  55 b:  66 c: 3
two parameters None


In [8]:
# We can use two different named arguments, they don't need to be in the correct positional order when named
display(c=9, a=11)

a:  11 b:  2 c: 9


In [10]:
# Positional arguments cannot come after named ones
# display(c=9, 44)
display(44, c=9)

a:  44 b:  2 c: 9


In [12]:
# help(numpy.loadtxt)

In [13]:
# readability of functions and code
def s(p):
    a = 0
    for v in p:
        a += v
    m = a/len(p)
    d = 0
    for v in p:
        d += (v-m) * (v-m)
    return numpy.sqrt(d/(len(p) -1))

def std_dev(sample):
    # this is a function for the standard deviation
    sample_sum = 0
    for value in sample:
        sample_sum += value

    sample_mean = sample_sum / len(sample)
    sum_squared_devs = 0
    for value in sample:
        sum_squared_devs += (value - sample_mean) * (value - sample_mean)

    return numpy.sqrt(sum_squared_devs / (len(sample) -1))

# Which one do you find more readable and why?
# It is good practice to name your functions and variables clearly
# This will help you to remember what you were doing in your code, but will help others too
# Every decision made in writing code gives context and additional information
# We want to write it in a way that anyone reading it won't have any questions
# We can do this with doc strings ("""text like this inside a function""") comments, and clear names

In [14]:
# we saw that you can add ( or concatentate) strings, can you write a function that will "wrap" a
# String inside another string? such that 
# print(fence("name", "*")
# will give output
# "*name*"
def fence(string, wrapping_str):
    # We can simply add our wrapping string to either side of the main string
    # Strings can be added to each other in Python
    output_str = wrapping_str + string + wrapping_str
    return output_str

fence("hello", " yay ")


' yay hello yay '

In [15]:
# return and print work differently, return gives the value back and print displays it
# what happens in the following?
def add(a,b):
    print(a + b)
    
A = add(7,3)
print(A)
# Print shows the value, and there is nothing returned
# So A has None value as default


10
None


In [19]:
# the str() function converts any datatype to a string
# can you write a function with 4 arguments, two of which have defaults
# that will convert all args to strings and add them together in one long string?

def stringifier(str_1, str_2, str_3="hello", str_4="world"):
    total_string = str(str_1) + str(str_2) + str(str_3) + str(str_4)
    return total_string

stringifier(str_1 = 555555, str_2 = True)
# Arguments with default values must not have arguments without defaults after
# e.g NO! func(a=1, b), YES! func(a, b=2) 

'555555Truehelloworld'

In [20]:
# Showing the difference between print and return in a function
def func_1(a, b):
    if a > 0:
        print("a is:" + str(a))
    return (a-b)

# The function prints a message, but it also returns a value
# In a notebook like this when naming a value or returning on at the end of a cell it will print the value out
func_1(3, 5)

a is:3


-2

In [22]:
# f-string
# fstrings are a form of string that allow you to feed in any value to the string between {}
# You can even perform calculations or function calls inside those brackets
a = 100
print(f"my grandma is {func_1(3,60)} year old")

a is:3
my grandma is -57 year old


In [ ]:
# An example you might use when debugging some code
print(f"this is breaking with value {value}")