## Data Analysis using numpy

In [4]:
# in this section we will be using numpy to load and analyse our dataset

In [53]:
# In order to use the external package we first need to import it
# If you don't have a package installed you can use '!pip install PACKAGE_NAME' to install it
import numpy

In [7]:
# We start by loading our data
numpy.loadtxt(fname="inflammation-01.csv", delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [8]:
# Loading the data means python will open the dataset and spit it out again
# In order to work with the data we first need to save it to a variable
data = numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")

In [9]:
# If we still want to see what it looks like then we can print out the dataset
# The columns are the days and the rows are patients in this inflammation dataset
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [10]:
# We have seen integers, strings, and floats, what data type is this object?
print(type(data))

<class 'numpy.ndarray'>


In [11]:
# We want to check the shape of the dataset
# this shape is an attribute of a numpy array, it shows that the object has 60 rows and 40 columns
data.shape

(60, 40)

In [12]:
# You can navigate arrays by indexing them
# To index you use the square brackets'[]' 
# Think of it like a coordinate system, 0,0 is the top left/first value
print("the first value is:", data[0,0])

the first value is: 0.0


In [13]:
# Python indexes start at 0, so the middle value is not quite at 30,20
print('middle value in data:', data[29, 19])

middle value in data: 16.0


In [15]:
# You can use ':' to  "slice" the data
# it will take from the first value and UP TO  and NOT INCLUDING the second value
# for example;
data[3:20, 2]

array([2., 1., 1., 2., 1., 0., 1., 0., 0., 2., 0., 2., 1., 0., 0., 2., 2.])

#### Can you slice the data to print out the first 3 patients and their first 9 days of data?

In [19]:
# Another example of slicing
list_test = [1,2,3,4,5,6,7,8,9,10]
list_test[2:5]

[3, 4, 5]

In [21]:
# first 3 patients and their first 9 days of data
# Method you can adjust in larger function calls
middle_pos = [0,0]
offset_col = 9
offset_row = 3
end_row_disp = middle_pos[0] + offset_row
end_col_disp = middle_pos[1] + offset_col
print(data[0:end_row_disp, 0:end_col_disp])
# using classic slicing
data[0:3, 0:9]

[[0. 0. 1.]
 [0. 1. 2.]
 [0. 1. 1.]
 [0. 0. 2.]
 [0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 2.]
 [0. 0. 1.]
 [0. 0. 0.]]


array([[0., 0., 1.],
       [0., 1., 2.],
       [0., 1., 1.],
       [0., 0., 2.],
       [0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [22]:
# What other functions does numpy have? 
# We can get the mean
print(numpy.mean(data))

6.14875


In [24]:
# In the above example you see that using a function needs the round brackets '()'
# For the numpy functions we have given an "argument", in this case, the data
# Not all functions need an argument though
# example of another package
import time
print(time.time())
# The time.time function doesn't need an argument as it just returns the current time (in number of seconds since 00:00 01/01/1970)
# This example below gets the current time, pauses for 3 seconds, and then checks the time again to see how long has passed
time_now = time.time()
time.sleep(3)
print(time.time() - time_now)

1772541644.917008
3.0057554244995117


In [ ]:
# the functions are amax and amin because ther is already a min and max function in Python
# from numpy import amax
# Above is a way to import a single function from a package

In [25]:
# We want to check a few key values from the dataset
maxval, minval, stdval = numpy.amax(data), numpy.amin(data), numpy.std(data)
print("max val: ", maxval)
print("min val: ", minval)
print("standard deviation: ", stdval)

max val:  20.0
min val:  0.0
standard deviation:  4.613833197118566


In [28]:
# You can always use the ? to find out more about the function
numpy.amin?

Signature:      
numpy.amin(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  numpy.amin(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function amin at 0x00000207C2A30720>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return the minimum of an array or minimum along an axis.

`amin` is an alias of `~numpy.min`.

See Also
--------
min : alias of this function
ndarray.min : equivalent method
Class docstring:
Class to wrap functions with checks for __array_function__ overrides.

All arguments are required, and can only be passed by position.

Parameters
----------
dispatcher : function or None
    The dispatcher function that returns a single sequence-like object
    of all arguments relevant.  It must have the same signature (except
    the default values) as the actual implementation.
    If ``None``, this is a ``like=`` disp

In [29]:
# What about if we want to analyse a section of the data?
patient_0 = data[0, :] # 0 in the first axis (rows) is one patient
patient_0

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [36]:
# this is the max inflammation for patient 0 across all days
print(numpy.amax(patient_0))

18.0


In [40]:
# axis 0 for columns, axis 1 for rows
# rows are patients, columns are days
print(numpy.amax(data, axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [43]:
# axis 0 for columns, axis 1 for rows
# rows are patients, columns are days
# Confusing, I know, it is the other way around likely as columns more often have a function applied to them than rows
print(numpy.amax(data, axis=1).shape)
print(numpy.amax(data, axis=0).shape)

(60,)
(40,)


In [54]:
string = "Matthew won't read the lesson"
# Can you slice this to spell hello world ?

In [55]:
print(string[4:6] +string[-6] + string[-6] + string[-2])

hello


In [47]:
# Can you rearrange the following matrix to use the first and last columns and stack into 3x2
# array instead?
A = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
B = numpy.array([A[:, 0], A[:,2]])
B = numpy.array([A[:, 0], A[:, 2]]).T
B

array([[1, 3],
       [4, 6],
       [7, 9]])

In [56]:
# The numpy.diff() function takes an array and returns the differences between two 
# successive values. Let’s use it to examine the changes each day across the first 
# week of patient 3 from our inflammation dataset.
patient3_week1 = data[3, :7]


In [58]:
print(patient3_week1)
# From left to right, the diff takes the difference between pairs of values
print(numpy.diff(patient3_week1))

[0. 0. 2. 0. 4. 2. 2.]
[ 0.  2. -2.  4. -2.  0.]


In [60]:
round(25.1) + 1

26